# Generated by Django 4.1.4 on 2022-12-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_food_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='img',
            new_name='imge',
        ),
    ]
