# Generated by Django 4.1.4 on 2022-12-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_img_food_imge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='imge',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
